name: Format on Push
on: push


jobs:
  clang-format:
    runs-on: self-hosted
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - run: clang-format-12 -i $(find . -iname '*.cpp' -or -iname '*.c' -or -iname '*.h' -and -not -iname 'doctest.h')
      - run: |
          git add .
          git commit -m "Automatic code format done by clang-format" || echo "Nothing to commit"
          git push || echo "Nothing to push"
